python ~/work/Bromide/PlotPowerSpectra.py \
	1/closest-water-oh1.dat \
	1/closest-water-oh2.dat \
	1/closest-water-oh3.dat \
	1/closest-water-oh4.dat \
	1/closest-water-oh5.dat \
	1/closest-water-oh6.dat \
	2/closest-water-oh1.dat \
	2/closest-water-oh2.dat \
	2/closest-water-oh3.dat \
	2/closest-water-oh4.dat \
	2/closest-water-oh5.dat \
	2/closest-water-oh6.dat \
	3/closest-water-oh1.dat \
	3/closest-water-oh2.dat \
	3/closest-water-oh3.dat \
	3/closest-water-oh4.dat \
	3/closest-water-oh5.dat \
	3/closest-water-oh6.dat \
	4/closest-water-oh1.dat \
	4/closest-water-oh2.dat \
	4/closest-water-oh3.dat \
	4/closest-water-oh4.dat \
	4/closest-water-oh5.dat \
	4/closest-water-oh6.dat \
	5/closest-water-oh1.dat \
	5/closest-water-oh2.dat \
	5/closest-water-oh3.dat \
	5/closest-water-oh4.dat \
	5/closest-water-oh5.dat \
	5/closest-water-oh6.dat
