python ~/work/Bromide/PlotPowerSpectra.py \
	6/closest-water-oh1.dat \
	6/closest-water-oh2.dat \
	6/closest-water-oh3.dat \
	6/closest-water-oh4.dat \
	6/closest-water-oh5.dat \
	6/closest-water-oh6.dat \
	7/closest-water-oh1.dat \
	7/closest-water-oh2.dat \
	7/closest-water-oh3.dat \
	7/closest-water-oh4.dat \
	7/closest-water-oh5.dat \
	7/closest-water-oh6.dat \
	8/closest-water-oh1.dat \
	8/closest-water-oh2.dat \
	8/closest-water-oh3.dat \
	8/closest-water-oh4.dat \
	8/closest-water-oh5.dat \
	8/closest-water-oh6.dat
	#9/closest-water-oh1.dat \
	#9/closest-water-oh2.dat \
	#9/closest-water-oh3.dat \
	#9/closest-water-oh4.dat \
	#9/closest-water-oh5.dat \
	#9/closest-water-oh6.dat \
	#10/closest-water-oh1.dat \
	#10/closest-water-oh2.dat \
	#10/closest-water-oh3.dat \
	#10/closest-water-oh4.dat \
	#10/closest-water-oh5.dat \
	#10/closest-water-oh6.dat \
